### ISSUE TITLE
TagBot is not working

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaData/StructTypes.jl#33]
See e.g. https://github.com/JuliaData/StructTypes.jl/runs/1541161385:
```
Processing version v1.2.0 (75c713f904949c0963bf54246397cab29d7aa63e)
Generating changelog for version v1.2.0 (75c713f904949c0963bf54246397cab29d7aa63e)
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
ERROR: Permission to JuliaData/StructTypes.jl.git denied to deploy key
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: TagBot experienced an unexpected internal failure
Traceback (most recent call last):
  File "/root/tagbot/action/__main__.py", line 91, in <module>
    repo.create_release(version, sha)
  File "/root/tagbot/action/repo.py", line 442, in create_release
    self._git.create_tag(version, sha, log)
  File "/root/tagbot/action/git.py", line 103, in create_tag
    self.command("push", "origin", version)
  File "/root/tagbot/action/git.py", line 69, in command
    raise Abort(f"Git command '{cmd}' failed")
tagbot.action.Abort: Git command 'git -C /tmp/tagbot_repo_vex2_4jk push origin v1.2.0' failed

Response (200): {
  "status": "Submitted error report"
}
```

**Comment by quinnj** [comment]
I've updated the missing keys
